# Generated by Django 4.1 on 2023-03-31 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_post_body"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-modified_date"]},
        ),
        migrations.AddField(
            model_name="post",
            name="modified_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
